project:
  type: website
  output-dir: docs

website:
  title: "Meme Habel"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - sidebar:tableau
      - sidebar:R

  sidebar: 
    - id: tableau
      title: "Tableau"
      contents: 
        - section: "Makeover Monday: AirHelp Scores" 
          contents: 
            - AirHelp_Abstract
            - AirHelp_Scores.qmd
      
    - id: R
      title: "R"
      contents: 
        - section: "Global Nutrition and Health"
          contents:
            - Capstone_Abstract.qmd
            - Capstone_Code.qmd
        - section: "Boston Housing Analysis"
          contents: 
            - BostonHousing_Abstract.qmd
            - BostonHousing_Code.qmd
            - BostonHousing_Presentation.qmd
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

