---
title: 'about'
title-block-banner: true
format:
    html:
      toc: true
      toc-depth: 4
callout-appearance: minimal
---

### Education

#### Graduate

##### - Master of Science in Business Analytics (MS)

  -   *Relevant Coursework:*
      -   Data Wrangling, Optimization, Data Mining, Simulation Modeling & Methods, Probability Models, Statistical Computing, Applied Statistical Methods, Applied Linear Regression, Data Management, Data Visualization, Survey of Machine Learning & Artificial Intelligence, and Forecasting Methods

#### Undergraduate

##### - Bachelor of Science in Business Analytics (BS)

##### - Bachelor of Scinece in Industrial Management (BSIM)


### Work Experience

*For additional information, please reference my resume.*

#### Pratt & Whitney: Global Supply Chain

##### - Center of Excellence Intern

  - Automated supplier chargeback process for late deliveries and quality issues based on Long Term Agreement (LTA) terms via a live dashboard which pulls in data from over 30 sources on a daily basis.

  - Learned Master Data protocols, completed SAP Bootcamp, and self-taught SQL/QlikSense Development.

  - *Tools utilized:* 
    - SQL, QlikSense, Microsoft Excel, VBA, Confluence, SAP

##### - Product Procurement Intern

<div class="custom-spacing">

  - Developed and deployed live automated line of balance system utilizing bill of materials, blueprints, lead times, and supplier commitments.

  - Led brainstorming, process mapping, and testing sessions with cross-functional teams.

  - *Tools utilized:* 
    - SQL, DBeaver, SAP, QlikSense, Metric Insights, Microsoft Project, Microsoft Visio, Microsoft Excel, VBA

</div>

##### - Indirect Procurement Analyst

  - Managed SAP Ariba system rollout to suppliers and led demonstrations.

  - Remidiated invoice discrepencies with in-depth analyses.

  - Analyzed Master Service Agreement (MSA) data and related invoices for sourcing team to identify trends in spending by category.

  - *Tools utilized:* 
    - SAP Ariba, SAP, RStudio, Microsoft Excel, VBA, QlikSense

### Skills

::: {.panel-tabset}

#### Technical Skills:

-   R/Rstudio
-   Python
-   Tableau
-   QlikSense

-   SQL

-   GitHub

-   Databricks

-   PySpark

-   Arena Simulation Software

-   MATLAB

-   LabVIEW

-   MySQL Workbench

-   Metric Insights

-   Microsoft

    -   Excel

    -   VBA

    -   SQL Server Management Studio

    -   Project

    -   Visio

    -   Access

    -   PowerPoint

    -   Word

    -   Outlook

    -   OneDrive

    -   SharePoint

    -   OneNote

    -   Teams

#### SAP Modules:

-   SAP Materials Management (SAP MM)

-   SAP Quality Management (SAP QM)

-   SAP Production Planning (SAP PP)

-   SAP Business Warehouse (SAP BW)

-   SAP Concur

-   SAP Ariba

#### Additional Skills:

-   Analytics

    -   Descriptive Analytics

    -   Predictive Analytics

    -   Prescriptive Analytics

    -   Data Visualization

    -   Optimization

    -   Simulation Modeling

    -   Forecasting

    -   Regression Analysis

    -   Probability and Statistical Modeling

    -   Data Management

    -   Survey Machine Learning and Artificial Intelligence

-   Project Management

-   Cross-Functional Collaboration

-   Leadership

-   Process Mapping

-   Continuous Improvement

-   Supplier Relationship Management

:::
